/**
 * useSosMock — hook giả lập dữ liệu SOS để dev/demo
 * Tọa độ được căn chỉnh chính xác theo địa chỉ thực tế tại Đà Nẵng
 */
export function useSosMock() {
  return {
    sosList: MOCK_SOS_LIST,
    loading: false,
    error: null,
  };
}

const MOCK_SOS_LIST = [
  {
    id: 'sos-001',
    victimName: 'Nguyễn Vũ Huy',
    victimPhone: '0373224840',
    incidentType: 'fire',
    description: 'Chân tôi bị chảy máu',
    status: 'active',
    priorityScore: 100,
    hasAudio: false,
    hasMedia: false,
    address: '470 Trần Đại Nghĩa, Ngũ Hành Sơn, Đà Nẵng',
    location: { lat: 16.0198, lng: 108.2448 },
  },
  {
    id: 'sos-002',
    victimName: 'Nguyễn Hải Nam',
    victimPhone: '0905118472',
    incidentType: 'natural_disaster',
    description: 'Tay tôi bị gãy',
    status: 'dispatched',
    priorityScore: 95,
    hasAudio: false,
    hasMedia: true,
    address: '92 Nguyễn Văn Linh, Hải Châu, Đà Nẵng',
    location: { lat: 16.0672, lng: 108.2145 },
  },
  {
    id: 'sos-003',
    victimName: 'Trần Thị Mai',
    victimPhone: '0912345678',
    incidentType: 'fire',
    description: 'Chân tôi bị chảy máu',
    status: 'active',
    priorityScore: 90,
    hasAudio: false,
    hasMedia: false,
    address: '15 Phan Chu Trinh, Hải Châu, Đà Nẵng',
    location: { lat: 16.0720, lng: 108.2230 },
  },
  {
    id: 'sos-004',
    victimName: 'Lê Văn Bình',
    victimPhone: '0987654321',
    incidentType: 'fire',
    description: 'Chân tôi bị chảy máu',
    status: 'active',
    priorityScore: 85,
    hasAudio: true,
    hasMedia: false,
    address: '123 Nguyễn Chí Thanh, Hải Châu, Đà Nẵng',
    location: { lat: 16.0635, lng: 108.2085 },
  },
  {
    id: 'sos-005',
    victimName: 'Phạm Thị Lan',
    victimPhone: '0901234567',
    incidentType: 'accident',
    description: 'Tôi bị tai nạn xe máy',
    status: 'active',
    priorityScore: 80,
    hasAudio: false,
    hasMedia: false,
    address: '88 Lê Duẩn, Hải Châu, Đà Nẵng',
    location: { lat: 16.0680, lng: 108.2265 },
  },
  {
    id: 'sos-006',
    victimName: 'Võ Minh Tuấn',
    victimPhone: '0356789012',
    incidentType: 'fire',
    description: 'Nhà tôi đang cháy',
    status: 'active',
    priorityScore: 75,
    hasAudio: true,
    hasMedia: true,
    address: '45 Hoàng Diệu, Hải Châu, Đà Nẵng',
    location: { lat: 16.0752, lng: 108.2162 },
  },
  {
    id: 'sos-007',
    victimName: 'Đinh Thị Hoa',
    victimPhone: '0789012345',
    incidentType: 'flood',
    description: 'Tôi bị mắc kẹt trong lũ',
    status: 'active',
    priorityScore: 70,
    address: '210 Núi Thành, Hải Châu, Đà Nẵng',
    // Núi Thành — phía nam Hải Châu
    location: { lat: 16.0528, lng: 108.2210 },
  },
  {
    id: 'sos-008',
    victimName: 'Hồ Văn Dũng',
    victimPhone: '0845678901',
    incidentType: 'fire',
    description: 'Chân tôi bị chảy máu',
    status: 'dispatched',
    priorityScore: 65,
    address: '332 Điện Biên Phủ, Thanh Khê, Đà Nẵng',
    // Điện Biên Phủ, Thanh Khê — phía tây bắc
    location: { lat: 16.0842, lng: 108.1990 },
  },
  {
    id: 'sos-009',
    victimName: 'Nguyễn Thị Thanh',
    victimPhone: '0934567890',
    incidentType: 'accident',
    description: 'Đầu tôi đang chảy máu',
    status: 'active',
    priorityScore: 60,
    address: '56 Hùng Vương, Hải Châu, Đà Nẵng',
    // Hùng Vương — bờ đông sông Hàn
    location: { lat: 16.0694, lng: 108.2188 },
  },
  {
    id: 'sos-010',
    victimName: 'Bùi Văn Khải',
    victimPhone: '0378901234',
    incidentType: 'fire',
    description: 'Chân tôi bị gãy',
    status: 'active',
    priorityScore: 55,
    address: '789 Tôn Đức Thắng, Liên Chiểu, Đà Nẵng',
    // Tôn Đức Thắng, Liên Chiểu — cực tây bắc TP
    location: { lat: 16.1058, lng: 108.1735 },
  },
];
